config:
  CHECKPOINT:
    AUTO_RESUME: true
    CHECKPOINT_FREQUENCY: 1000
    CHECKPOINT_ITER_FREQUENCY: -1
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TEST:
      BATCHSIZE_PER_REPLICA: 256
      DATASET_NAMES:
      - imagenet1k_folder
      DATA_SOURCES:
      - disk_folder
      LABEL_TYPE: sample_index
      TRANSFORMS:
      - name: Resize
        size: 256
      - name: CenterCrop
        size: 224
      - name: ToTensor
      - mean:
        - 0.485
        - 0.456
        - 0.406
        name: Normalize
        std:
        - 0.229
        - 0.224
        - 0.225
    TRAIN:
      BATCHSIZE_PER_REPLICA: 256
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      COPY_TO_LOCAL_DISK: false
      DATASET_NAMES:
      - imagenet1k_folder
      DATA_SOURCES:
      - disk_folder
      DROP_LAST: true
      LABEL_TYPE: sample_index
      MMAP_MODE: true
      TRANSFORMS:
      - name: RandomResizedCrop
        size: 224
      - name: RandomHorizontalFlip
      - name: ToTensor
      - mean:
        - 0.485
        - 0.456
        - 0.406
        name: Normalize
        std:
        - 0.229
        - 0.224
        - 0.225
  DISTRIBUTED:
    BACKEND: nccl
    INIT_METHOD: tcp
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
    RUN_ID: auto
  HOOKS:
    PERF_STATS:
      MONITOR_PERF_STATS: true
      ROLLING_BTIME_FREQ: 313
    TENSORBOARD_SETUP:
      EXPERIMENT_LOG_DIR: moco_v2_reference
      FLUSH_EVERY_N_MIN: 20
      LOG_PARAMS: false
      USE_TENSORBOARD: true
  LOG_FREQUENCY: 200
  LOSS:
    cross_entropy_multiple_output_single_target:
      ignore_index: -1
    name: cross_entropy_multiple_output_single_target
  MACHINE:
    DEVICE: gpu
  METERS:
    accuracy_list_meter:
      num_meters: 5
      topk_values:
      - 1
    name: accuracy_list_meter
  MODEL:
    AMP_PARAMS:
      USE_AMP: false
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: true
      FREEZE_TRUNK_ONLY: true
    HEAD:
      PARAMS:
      - - mlp
        - dims:
          - 512
          - 2
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: false
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 18
  MULTI_PROCESSING_METHOD: forkserver
  OPTIMIZER:
    momentum: 0.9
    name: sgd
    nesterov: true
    num_epochs: 28
    param_schedulers:
      lr:
        auto_lr_scaling:
          auto_scale: true
          base_lr_batch_size: 256
          base_value: 0.01
        milestones:
        - 8
        - 16
        - 24
        name: multistep
        update_interval: epoch
        values:
        - 0.01
        - 0.001
        - 0.0001
        - 1.0e-05
    regularize_bias: true
    regularize_bn: false
    weight_decay: 0.0005
  SEED_VALUE: 0
  TEST_MODEL: true
  TEST_ONLY: false
  TRAINER:
    TRAIN_STEP_NAME: standard_train_step
  VERBOSE: false
